//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod address;
pub mod categories;
pub mod colors;
pub mod customer;
pub mod product;
pub mod product_review;
pub mod sizes;
