//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::address::Entity as Address;
pub use super::categories::Entity as Categories;
pub use super::colors::Entity as Colors;
pub use super::customer::Entity as Customer;
pub use super::product::Entity as Product;
pub use super::product_review::Entity as ProductReview;
pub use super::sizes::Entity as Sizes;
