CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	username VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	telephone VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	token TEXT DEFAULT NULL,
)
CREATE TABLE IF NOT EXISTS admin(
	id SERIAL PRIMARY KEY,
	username VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	telephone VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	token TEXT DEFAULT NULL,
)
CREATE TABLE IF NOT EXISTS products(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	price DECIMAL NOT NULL,
	stock INT NOT NULL,
	description TEXT NOT NULL,
)

